Получение и отображение данных
IlyaKrasovickij03/sofia-apps pull request #1
Opened 2024-06-23 10:27 UTC by IlyaKrasovickij03

2024-06-24 13:59 UTC, IlyaKrasovickij03 commented on apps/sofia-main/app/src/main/java/com/mk_sofia/sofiamain/presentation/categories_screen/CategoriesScreen.kt
> +    viewModel.event(CategoriesContract.Event.GetAllCategories)
Не уверен, насколько это адекватный вариант - в composable сначала дергать метод на получение данных, а затем отображать в стейте. Нужен совет, не знаю, как здесь лучше поступить с точки зрения архитектуры

2024-06-25 06:23 UTC, Ziggsy requested changes

2024-06-25 06:23 UTC, Ziggsy commented on apps/sofia-main/app/src/main/java/com/mk_sofia/sofiamain/presentation/categories_screen/CategoriesScreen.kt
> +    viewModel.event(CategoriesContract.Event.GetAllCategories)
Поскольку это init метод экрана, я бы сунул его во viewModel `init`

```
    init {
       getAllCategories()
    }
```

Это так же можно реализовать через 

```
    LaunchedEffect(Unit) {
        viewModel.event(CategoriesContract.Event.GetAllCategories)
    }
```

Но этот вариант мне нравится меньше, ибо при реконфигурации мы будем делать лишний запрос

2024-06-25 06:23 UTC, Ziggsy commented on apps/sofia-main/app/src/main/java/com/mk_sofia/sofiamain/presentation/categories_screen/CategoriesViewModel.kt
> +            val categories = sofiaRepository.getAllCategories()
В идеальном мире, твой UI слой не должен ничего знать про Data слой, всё должно идти через Domain. 

Т.е. у тебя тут должен быть проксирующий Usecase

2024-06-25 06:23 UTC, Ziggsy commented on apps/sofia-main/app/src/main/java/com/mk_sofia/sofiamain/presentation/categories_screen/CategoriesViewModel.kt
> +            val categories = sofiaRepository.getAllCategories()
Весь код `sofiaRepository.getAllCategories()` кроме вызова ретрофита (он автоматически переключает на свой диспатчер) будет выполняться на основном потоке.

Сейчас это не критично, ибо в коде мы только мапим, но если в будущем туда добавить тяжелую операцию, то будет плохо для UI

2024-06-25 06:23 UTC, Ziggsy commented on apps/sofia-main/app/src/main/java/com/mk_sofia/sofiamain/presentation/categories_screen/CategoriesViewModel.kt
> +    internal class Factory(
Работал ли ты с [koin](https://insert-koin.io/)? Может сразу втащим что бы избавиться от этого?

2024-06-25 07:23 UTC, IlyaKrasovickij03 commented on apps/sofia-main/app/src/main/java/com/mk_sofia/sofiamain/presentation/categories_screen/CategoriesScreen.kt
> +    viewModel.event(CategoriesContract.Event.GetAllCategories)
Согласен. ЛаунчЭффект не подходит совсем. А про инит я забыл, хорошая идея

2024-06-25 07:24 UTC, IlyaKrasovickij03 commented on apps/sofia-main/app/src/main/java/com/mk_sofia/sofiamain/presentation/categories_screen/CategoriesViewModel.kt
> +            val categories = sofiaRepository.getAllCategories()
Окей, сделаем

2024-06-25 07:27 UTC, IlyaKrasovickij03 commented on apps/sofia-main/app/src/main/java/com/mk_sofia/sofiamain/presentation/categories_screen/CategoriesViewModel.kt
> +    internal class Factory(
Думал, внедрение DI - это следующий шаг. Я даже без понятния, как обычно этот DI начинают. Это же прям вообще отдельная тема

2024-06-25 07:29 UTC, IlyaKrasovickij03 commented on apps/sofia-main/app/src/main/java/com/mk_sofia/sofiamain/presentation/categories_screen/CategoriesViewModel.kt
> +            val categories = sofiaRepository.getAllCategories()
`будет выполняться на основном потоке`
Не понял, почему? Я же во viewModelScope закинул

2024-06-25 20:14 UTC, Ziggsy commented on apps/sofia-main/app/src/main/java/com/mk_sofia/sofiamain/presentation/categories_screen/CategoriesViewModel.kt
> +    internal class Factory(
Можем пока оставить без DI, на koin супер простой. Он по сути даже не DI, а сервис локатор, он просто упростит создание всяких репозиториев и тд

Дагер точно будет избыточен

2024-06-30 15:04 UTC, merged